import dotenv from "dotenv";
import express from "express";
import cors from "cors";
import authRoute from "./route/auth.route";
import userRoute from "./route/user.route";
import productRoute from "./routes/product.route";
import bodyParser from "body-parser";
import initWebRoutes from "./route/web";
dotenv.config();
const app = express();
app.use(cors({ origin: true, credentials: true }));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use("/api/auth", authRoute);
app.use("/api/users", userRoute);
app.use("/api/products", productRoute);
initWebRoutes(app);
const port = process.env.PORT || 6969;
app.listen(port, () => {
  console.log(`Backend running at http://localhost:${port}`);
});
